# Welcome to Numpy Tutorial

In [7]:
import numpy as np

In [3]:
arr1 = np.array([3,6,32,7], np.int8)    # 1-D array

In [27]:
arr1

array([ 3,  6, 32,  7], dtype=int8)

In [28]:
arr1[3]    # returns the element at index 3 in the array

7

In [29]:
arr2 = np.array([[3,5,6,7]])    # 2-D array

In [30]:
arr2[0,2] # returns the element in row 0 and column 2

6

In [31]:
arr2.shape  # returns (no. of rows, no. of columns)

(1, 4)

In [32]:
arr1.shape 

(4,)

In [33]:
arr2.dtype

dtype('int32')

In [ ]:
arr2[0,1] = 45  # changing element of an array

In [35]:
arr2

array([[ 3, 45,  6,  7]])

# Methods to create NumPy arrays
5 methods:
1. Conversion from other Py structures(list, tuples)
2. Intrinsic numpy array creation objects
3. Reading arrays from disk, either from standard or custom formats
4. Creating arrays form raw bytes thrugh the use of strings or buffers
5. Use of special library function(e.g. random)

** 1. Conversion from other Py structures(list, tuples) **

In [36]:
listarray = np.array([[1,2,3],[4,3,5],[4,65,7]])

In [37]:
listarray

array([[ 1,  2,  3],
       [ 4,  3,  5],
       [ 4, 65,  7]])

In [38]:
listarray.dtype

dtype('int32')

In [40]:
listarray.shape

(3, 3)

In [42]:
listarray.size   # returns the no. of elements in the array

9

** 2. Intrinsic numpy array creation objects(e.g. arange, ones, zeroes, etc.) **
** These are the builtin function provided by numpy to built arrays **

In [56]:
zeros = np.zeros((2,5))   # create an array of specified shape with all elements as 0(float value as default)

In [57]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
zeros.size

10

In [50]:
zeros.shape

(2, 5)

In [52]:
zeros.dtype

dtype('float64')

In [ ]:
rng = np.arange(15)   # similar to py's range function (arange = array range)

In [59]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
# np.linspace(start element, end element, no. of elements)  -> it will return elements having equal difference
# default dtype = float
lspace = np.linspace (1, 5, 12)   #return an array having 12 elements between 1 to 5 having equal spaces between them

In [14]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [17]:
# returns an empty array of random value which can be assigned later
emp = np.empty((3,4))  #returns an array of specified shape having random elements

In [18]:
emp

array([[1.        , 1.36363636, 1.72727273, 2.09090909],
       [2.45454545, 2.81818182, 3.18181818, 3.54545455],
       [3.90909091, 4.27272727, 4.63636364, 5.        ]])

In [15]:
emp_like = np.empty_like(lspace)   # similar to empty but instead of random value we can use our specified values and array shape

In [16]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [ ]:
ide = np.identity(3)  # returns an identity matrix of specified row/column 

In [20]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
ide.shape

(3, 3)

In [ ]:
# To reshape an array created using range function
arr3 = np.arange(33)

In [23]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [ ]:
arr3.reshape(3,11)  # this will create a copy & will not change the actual value

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]])

In [28]:
arr3 = arr3.reshape(11,3)  # this will change the actual value of arr3

In [29]:
arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32]])

In [31]:
# again converting arr3 to 1D array
arr3 = arr3.ravel()

In [33]:
arr3.shape

(33,)

## Axis Concept

In [34]:
arr4 = np.array([[1,2,3],[4,5,6],[7,1,0]])

In [35]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [36]:
arr4.sum(axis = 0)

array([12,  8,  9])

In [37]:
arr4.sum(axis = 1)

array([ 6, 15,  8])

In [ ]:
# Transpose of a Matrix
arr4.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [ ]:
arr4.flat   #gives an iterator

In [43]:
for item in arr4.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [ ]:
# No. of dimensions = ndim (x & y)
arr4.ndim

2

In [45]:
arr4.size

9

In [105]:
arr4.nbytes  #returns total bytes consumed

36

In [56]:
one = np.array([1,3,4,643,3])

In [ ]:
one.argmax()   # gives index of the maximum element

3

In [57]:
one.argmin()   # returns the index of the minimun element

0

In [ ]:
one.argsort()  # returns indices of the elements(in sorted order)

array([0, 1, 4, 2, 3], dtype=int64)

In [68]:
arr5 = np.array([[1,2,3],[4,0,4],[3,5,6]])

In [69]:
arr5

array([[1, 2, 3],
       [4, 0, 4],
       [3, 5, 6]])

In [70]:
arr5.argmin()

4

In [71]:
arr5.argmax()

8

In [ ]:
arr5.argmax(axis=0)  #returns the indices of max elements w.r.t. axis 0
# [index of max element in column 0, column 1, column 2]

array([1, 2, 2], dtype=int64)

In [ ]:
arr5.argmax(axis=1)  #returns the indices of max elements w.r.t. axis 1
# [index of max element in row 0, row 1, row 2]

array([2, 0, 2], dtype=int64)

In [ ]:
arr5.argsort()   # by default, axis=1 (row-wise sort)

array([[0, 1, 2],
       [1, 0, 2],
       [0, 1, 2]], dtype=int64)

In [ ]:
arr5.argsort(axis = 0)  # this will sort column-wise

array([[0, 1, 0],
       [2, 0, 1],
       [1, 2, 2]], dtype=int64)

In [82]:
arr5.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [0],
       [4],
       [3],
       [5],
       [6]])

## Mathematical operations on NumPy arrays

In [83]:
arr5

array([[1, 2, 3],
       [4, 0, 4],
       [3, 5, 6]])

In [86]:
arr6 = np.array([[1,4,3],
                [4,0,6],
                [8,1,0]])

In [87]:
arr6

array([[1, 4, 3],
       [4, 0, 6],
       [8, 1, 0]])

In [ ]:
arr5 + arr6    #this will create a copy & will not change the actual data of any of the array

array([[ 2,  6,  6],
       [ 8,  0, 10],
       [11,  6,  6]])

In [ ]:
arr5 * arr6   # it will multiply element-wise & not as per mathematical matrices

array([[ 1,  8,  9],
       [16,  0, 24],
       [24,  5,  0]])

In [ ]:
np.sqrt(arr6)   # return an array having square root of the elements

array([[1.        , 2.        , 1.73205081],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 0.        ]])

In [ ]:
arr6.sum()  #returns sum of the elements of arr6

27

In [ ]:
arr6.max()  # max element in arr6

8

# Finding an element in an NumPy array

In [93]:
arr6

array([[1, 4, 3],
       [4, 0, 6],
       [8, 1, 0]])

In [ ]:
np.where(arr6>5)   #It returns tuple of an array according to specified condition

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [95]:
type(np.where(arr6>5))

tuple

In [113]:
np.count_nonzero(arr6)    #count no. of non-zero elements in an array

7

In [114]:
np.column_stack([1,23,4,5,6])     #Stack elements of 1-D arrays as columns into a 2-D array

array([[ 1, 23,  4,  5,  6]])

In [115]:
np.nonzero(arr6)   #Return the indices of the elements that are non-zero as tuples

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 0, 1], dtype=int64))

# How NumPy array are more space effective than Py array?

In [116]:
import sys

In [8]:
py_ar = [0, 4, 55, 2]

In [9]:
np_ar = np.array(py_ar)

In [ ]:
sys.getsizeof(1) * len(py_ar)    # size of 1 element * len of array = total size of array

112

In [12]:
np_ar.nbytes

16

In [121]:
np_ar.itemsize * np_ar.size   # size of 1 item in array * size(no. of elements) of the array = total size of array

16

In [13]:
np_ar.tolist()   #converts numpy array to list

[0, 4, 55, 2]